# NumPy Array Indexing and Slicing

### 1D Array Indexing and Sliding

In [1]:
import numpy as np

In [2]:
a = np.arange(5) ** 2
a

array([ 0,  1,  4,  9, 16], dtype=int32)

In [3]:
a[2]

4

In [4]:
a[2:5]  # From 2 (included) to 5 (excluded)

array([ 4,  9, 16], dtype=int32)

In [5]:
a[:4:2]  # From 2 (included) to 4 (excluded) with a step 2

array([0, 4], dtype=int32)

In [6]:
a[:4:2] = -100
a

array([-100,    1, -100,    9,   16], dtype=int32)

In [7]:
a[::-1]  #Reverse (not done in place)

array([  16,    9, -100,    1, -100], dtype=int32)

In [8]:
a

array([-100,    1, -100,    9,   16], dtype=int32)

### 2D Array Indexing

In [9]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
a[1]

array([3, 4, 5])

In [11]:
a[1][1]

4

In [12]:
a[1, 1]  #Preferred

4

### Compare with Indexing of a List of Lists

In [13]:
b = [[0, 1, 2], [3, 4, 5]]
b

[[0, 1, 2], [3, 4, 5]]

In [14]:
b[1]

[3, 4, 5]

In [15]:
b[1][1]

4

- `b[1, 1]` does not work.<br>

### 2D Array Slicing

In [16]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
a[1, 2:4]  # Red cells

array([7, 8])

In [18]:
a[3:, 3:]  # Green cells

array([[18, 19],
       [23, 24]])

<img src="images/2d_indexing.png" alt="2D Indexing", style="width: 150px;"/>

In [19]:
a[:, 1]  # Purple cells

array([ 1,  6, 11, 16, 21])

In [20]:
a[::2, 2::2]  # Yellow cells

array([[ 2,  4],
       [12, 14],
       [22, 24]])

### Fancy Indexing with Arrays of Integers

In [21]:
a = np.arange(5)**2  # Data array         
a

array([ 0,  1,  4,  9, 16], dtype=int32)

In [22]:
i = np.array([3, 1, 3, 0])  # Index array
i

array([3, 1, 3, 0])

In [23]:
a[i]  # The shape is determined by the index array
      # The elements come from the data array.

array([9, 1, 9, 0], dtype=int32)

In [24]:
a  # Data array

array([ 0,  1,  4,  9, 16], dtype=int32)

In [25]:
j = np.array([[0,3], [2,1]])  #2D index array
j

array([[0, 3],
       [2, 1]])

In [26]:
a[j]  # The shape is determined by the index array
      # The elements come from the data array.

array([[0, 9],
       [4, 1]], dtype=int32)

In [27]:
c = np.arange(12).reshape(3, 4)  # Data array
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
i = np.array([[0, 1], [1, 2]])  # Index array
i

array([[0, 1],
       [1, 2]])

In [29]:
j = np.array([[2, 1], [3, 3]])  # Index array
j

array([[2, 1],
       [3, 3]])

In [30]:
c[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [31]:
c[i, j]  # The index arrays for each dimension must have the same shape

array([[ 2,  5],
       [ 7, 11]])

In [32]:
c[i, j]=-1  # Use indexing to assign values
c

array([[ 0,  1, -1,  3],
       [ 4, -1,  6, -1],
       [ 8,  9, 10, -1]])

### Fancy Indexing with Boolean Arrays

In [33]:
a = np.arange(9).reshape(3, 3)  # Data array
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
b = a > 4  # Index array
b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [35]:
a[b]

array([5, 6, 7, 8])

In [36]:
a[b] = -1  # Assign new values
a  # New data array

array([[ 0,  1,  2],
       [ 3,  4, -1],
       [-1, -1, -1]])

In [37]:
i = np.array([False, True, True])  # Index array
i

array([False,  True,  True], dtype=bool)

In [38]:
j = np.array([True, False, True])  # Index array
j

array([ True, False,  True], dtype=bool)

In [39]:
a[i, :]

array([[ 3,  4, -1],
       [-1, -1, -1]])

In [40]:
a[:, j]

array([[ 0,  2],
       [ 3, -1],
       [-1, -1]])

### More About Fancy Indexing

In [41]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
a[(0, 2, 4), (0, 2, 4)]  # Red cells

array([ 0, 12, 24])

In [43]:
a[[1, 3, 4], 3:]  # Green cells

array([[ 8,  9],
       [18, 19],
       [23, 24]])

<img src="images/2d_fancy_indexing.png" alt="2D Fancy Indexing", style="width: 150px;"/>

In [44]:
mask = np.array([0, 1, 1, 1, 0], dtype=bool)
mask

array([False,  True,  True,  True, False], dtype=bool)

In [45]:
a[1, mask]  # Purple cells

array([6, 7, 8])

In [46]:
imesh = np.ix_([1, 4], np.r_[0, 2:4])  # Index mesh
imesh

(array([[1],
        [4]]), array([[0, 2, 3]]))

In [47]:
a[imesh]  # Yellow cells

array([[ 5,  7,  8],
       [20, 22, 23]])

### Array Stacking

In [48]:
a = np.array([[0, 1], [2, 3]])
a

array([[0, 1],
       [2, 3]])

In [49]:
b = np.array([[0, -1], [-2, -3]])
b

array([[ 0, -1],
       [-2, -3]])

In [50]:
np.vstack([a, b])  # Lists or tuples
                   # np.vstack(a, b) does not work

array([[ 0,  1],
       [ 2,  3],
       [ 0, -1],
       [-2, -3]])

In [51]:
np.hstack((a, b))  # Lists or tuples
                   # np.hstack(a, b) does not work

array([[ 0,  1,  0, -1],
       [ 2,  3, -2, -3]])

### Array Splitting

In [52]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
np.vsplit(a, 3)  # Split vertically (row-wise)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [54]:
np.hsplit(a, 3)  # Split horizontally (column-wise)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

### Course Materials on YouTube and GitHub

- Course videos are hosted by YouTube (http://youtube.com/yongtwang).
- Course documents (Jupyter Notebooks and Python source code) are hosted by GitHub (http://github.com/yongtwang).