# NumPy Array Broadcasting

### The Basics

- Broadcasting is the way used by NumPy when dealing with arrays of different shapes during arithmetic operations.

In [1]:
import numpy as np

In [2]:
a = np.arange(3)
a

array([0, 1, 2])

In [3]:
b = 1
b

1

In [4]:
a + b

array([1, 2, 3])

<img src="images/broadcast1.png" alt="Broadcast 1" style="width: 300px;"/>

In [5]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [7]:
a + b

array([[0, 2, 4],
       [3, 5, 7]])

<img src="images/broadcast2.png" alt="Broadcast 2" style="width: 300px;"/>

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b = np.array([0, 1]).reshape(2, 1)
b

array([[0],
       [1]])

In [10]:
a + b

array([[0, 1, 2],
       [4, 5, 6]])

<img src="images/broadcast3.png" alt="Broadcast 3" style="width: 300px;"/>

In [11]:
b = 2
b

2

In [12]:
a + b

array([[2, 3, 4],
       [5, 6, 7]])

<img src="images/broadcast4.png" alt="Broadcast 4" style="width: 300px;"/>

In [13]:
a = np.array([0, 3]).reshape(2, 1)
a

array([[0],
       [3]])

In [14]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [15]:
a + b

array([[0, 1, 2],
       [3, 4, 5]])

<img src="images/broadcast5.png" alt="Broadcast 5" style="width: 300px;"/>

- If the dimensions mismatch, there will be an error.
<img src="images/broadcast_mismatch.png" alt="Broadcast Mismatch" style="width: 250px;"/>

### Example

- Calculate the distances between any two cities (Binghamton, Hancock, Middletown, Sloatsburg, NYC) on the route from Binghamton to NYC.
<img src="images/binghamton2nyc.png" alt="Binghamton to NYC" style="width: 250px;"/>

In [16]:
miles = np.array([0, 43, 120, 153, 190])  # Distances from Binghamton to each of these cities
miles

array([  0,  43, 120, 153, 190])

In [17]:
miles.reshape(5, 1)

array([[  0],
       [ 43],
       [120],
       [153],
       [190]])

In [18]:
miles - miles.reshape(5, 1)  # Distances between any two cities

array([[   0,   43,  120,  153,  190],
       [ -43,    0,   77,  110,  147],
       [-120,  -77,    0,   33,   70],
       [-153, -110,  -33,    0,   37],
       [-190, -147,  -70,  -37,    0]])

### Course Materials on YouTube and GitHub

- Course videos are hosted by YouTube ( http://youtube.com/yongtwang ).
- Course documents (Jupyter Notebooks and Python source code) are hosted by GitHub ( http://github.com/yongtwang ).