# NumPy Quick Start (Part 2 of 2)

### Statistics

In [1]:
import numpy as np

In [2]:
a = np.array([[0,1], [2,3]])
a

array([[0, 1],
       [2, 3]])

In [3]:
np.sum(a)

6

In [4]:
np.sum(a, axis=0)  # Sum of each column

array([2, 4])

In [5]:
np.sum(a, axis=1)  # Sum of each row

array([1, 5])

In [6]:
a

array([[0, 1],
       [2, 3]])

In [7]:
np.min(a)

0

In [8]:
np.max(a)

3

In [9]:
np.mean(a)

1.5

In [10]:
a

array([[0, 1],
       [2, 3]])

In [11]:
np.median(a)

1.5

In [12]:
np.var(a)

1.25

In [13]:
np.std(a)

1.1180339887498949

### Linear Algebra Operations

In [14]:
a

array([[0, 1],
       [2, 3]])

In [15]:
np.transpose(a)

array([[0, 2],
       [1, 3]])

In [16]:
np.linalg.inv(a)  # The inverse matrix

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [17]:
b = np.array([[5], [7]])
b

array([[5],
       [7]])

- Solve $\textbf{ax = b} \Rightarrow 
\begin{bmatrix} 
0 & 1 \\
2 & 3 
\end{bmatrix}
\begin{bmatrix} 
x_1 \\
x_2 
\end{bmatrix}
=
\begin{bmatrix} 
5 \\
7 
\end{bmatrix}
$ for **x**.

In [18]:
np.linalg.solve(a, b)  # Solve ax = b for x

array([[-4.],
       [ 5.]])

- Find the determinant $
\begin{vmatrix} 
0 & 1 \\
2 & 3 
\end{vmatrix}
$.

In [19]:
np.linalg.det(a)

-2.0

In [20]:
np.diag(a)  # Find the diagonal elements

array([0, 3])

In [21]:
np.trace(a)  # Sum of the diagonal elements

3

- Other commonly used LA functions:
    - eig: Compute the eigenvalues and eigenvectors of a square matrix
    - pinv: Compute the Moore-Penrose pseudo-inverse of a matrix
    - qr: Compute the QR decomposition
    - svd: Compute the singular value decomposition (SVD)
    - lstsq: Compute the least-squares solution to Ax = b

### Random Number Generators

In [22]:
samples = np.random.normal(85, 10, size=(4, 4))
samples

array([[ 90.10582394,  87.60328998,  89.4793263 ,  68.28898926],
       [ 71.2806284 ,  82.68141845,  71.41131351,  86.10264547],
       [ 72.29085631,  90.57799908,  86.75253703,  86.08312056],
       [ 79.14148276,  70.44717286,  90.00585297,  75.30508122]])

In [23]:
samples = np.random.randn(4, 4)
samples

array([[ 0.32902994, -0.49049036,  0.02629103,  1.56458542],
       [-1.30976155,  0.51349796, -0.5691113 , -0.18107008],
       [-1.92470206,  0.80308502,  0.0524378 , -1.25027981],
       [-1.20015242, -1.6169179 ,  0.49395041, -1.18763417]])

In [24]:
samples = np.random.randn(100, 100)
samples.mean()

-0.0062997978817707937

In [25]:
samples.std()

0.99281861891163392

In [26]:
a = list(range(5))
a

[0, 1, 2, 3, 4]

In [27]:
np.random.permutation(a)

array([1, 4, 2, 0, 3])

In [28]:
np.random.permutation(a)

array([2, 1, 4, 3, 0])

In [29]:
a

[0, 1, 2, 3, 4]

In [30]:
np.random.shuffle(a)  # Randomly permute a sequence in place

In [31]:
a

[2, 1, 0, 4, 3]

- Other commonly used random number functions:
    - seed: Seed the random number generator
    - uniform: Draw samples from a uniform [low, high) distribution
    - randint: Draw random integers from a discrete uniform [low, high) distribution
    - binomial: Draw samples from a binomial distribution
    - beta: Draw samples from a beta distribution
    - chisquare: Draw samples from a chi-square distribution
    - gamma: Draw samples from a gamma distribution

### Logic Operations

In [32]:
a = [True, True, False]
a

[True, True, False]

In [33]:
np.all(a)  # All true?

False

In [34]:
np.any(a)  # Any true?

True

In [35]:
a = np.zeros((3, 3))
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [36]:
a == 0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [37]:
np.all(a == 0)

True

In [38]:
a != 0

array([[False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [39]:
np.any(a != 0)

False

### Sorting

In [40]:
a = np.random.randn(5)
a

array([-0.23412906, -0.55102101, -0.7308064 , -0.09678327,  0.6862942 ])

In [41]:
a.sort()  # Sorting is done in-place
a

array([-0.7308064 , -0.55102101, -0.23412906, -0.09678327,  0.6862942 ])

In [42]:
b = np.random.randn(3, 3)
b

array([[ 0.30848454,  0.7412512 , -0.2267951 ],
       [ 1.740978  ,  1.04612534, -1.07621028],
       [ 0.82354044, -0.6718184 , -0.75459861]])

In [43]:
b.sort(axis=1)  # Along each row (default)
b

array([[-0.2267951 ,  0.30848454,  0.7412512 ],
       [-1.07621028,  1.04612534,  1.740978  ],
       [-0.75459861, -0.6718184 ,  0.82354044]])

In [44]:
b.sort(axis=0)  # Then along each column
b

array([[-1.07621028, -0.6718184 ,  0.7412512 ],
       [-0.75459861,  0.30848454,  0.82354044],
       [-0.2267951 ,  1.04612534,  1.740978  ]])

### Row and Column Vectors

- NumPy does not differentiate between 1D row and 1D column vectors.

In [45]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [46]:
b = a.transpose()
b

array([1, 2, 3])

- A column vector can only be represented by a 2D array.

In [47]:
b = np.array([[1], [2], [3]])
b

array([[1],
       [2],
       [3]])

In [48]:
b.transpose()  # Transposing is not done in-place

array([[1, 2, 3]])

In [49]:
b

array([[1],
       [2],
       [3]])

- We can also use `reshape` to make a 2D column array.

In [50]:
np.array([1, 2, 3]).reshape(3, 1)

array([[1],
       [2],
       [3]])

- `r_` and `c_` create arrays by stacking numbers along one axis.

In [51]:
a = np.r_[-2, -1, 1:4]  # Skip over 0
a

array([-2, -1,  1,  2,  3])

In [52]:
np.c_[a]

array([[-2],
       [-1],
       [ 1],
       [ 2],
       [ 3]])

### Course Materials on YouTube and GitHub

- Course videos are hosted by YouTube ( http://youtube.com/yongtwang ).
- Course documents (Jupyter Notebooks and Python source code) are hosted by GitHub ( http://github.com/yongtwang ).