# NumPy Quick Start (Part 1 of 2)

### The Basics

- NumPy is a Python library that provides fast operations on multi-dimensional arrays.
- [NumPy and MATLAB have a lot in common, but they also have many differences](https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html).
- An ndarray object is a homogeneous (the elements are all of the same type) multi-dimensional array.
- NymPy array operations are much faster than Python `for` and `while` loops. Watch [this YouTube video](https://www.youtube.com/watch?v=EEUXKG97YRw).

In [1]:
import numpy as np

### Array Creation

In [2]:
a = np.array([0, 1, 2, 3])  # 1D array from a list
a

array([0, 1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array((0, 1, 2, 3))  # 1D array from a tuple
a                           # np.array(0, 1, 2, 3) does not work

array([0, 1, 2, 3])

In [5]:
b = np.array([[0, 1], [2, 3]])  # 2D array from a list of lists
b

array([[0, 1],
       [2, 3]])

In [6]:
c = np.array([3, '4.5'])  # Homogeneous data type

- `np.array([3, '4.5', [1, -2]])` will produce an error. We can modify it in the following two ways:

In [7]:
c = np.array([3, '4.5', 1, -2])
c

array(['3', '4.5', '1', '-2'],
      dtype='<U11')

In [8]:
c = np.array([[3, '4.5'], [1, -2]])
c

array([['3', '4.5'],
       ['1', '-2']],
      dtype='<U11')

In [9]:
c = np.arange(6)  # Returns an array instead of a list
c

array([0, 1, 2, 3, 4, 5])

In [10]:
np.arange(-2, 1, 0.5)  # Interval is 0.5

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5])

- `range(-2, 1, 0.5)` does not work.

In [11]:
np.linspace(0, 2, 5)  # 5 elements equally distributed
                      # between 0 and 2 (inclusive)

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [12]:
np.ones([2, 3])  # Array of ones


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
np.zeros([2, 3])  # Array of zeros

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
np.zeros((2, 3))  # np.zeros(2, 3) does not work

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [16]:
u = np.eye(2)  # 2D unit array
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [17]:
a = np.array([1, 2, 3])
d = np.diag(a)  # 2D diagonal array
d

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Array Attributes

In [18]:
d.ndim  # Number of dimensions 

2

In [19]:
d.shape # Length of each dimension

(3, 3)

In [20]:
d.size  # Total number of elements

9

### Array Reshaping

In [21]:
c = np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

In [22]:
c.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
c  # Reshaping is not done in-place

array([0, 1, 2, 3, 4, 5])

In [24]:
c = c.reshape(2, 3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
c.reshape((3, -1))  # -1 means unspecified

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
c.ravel()  # Flattening

array([0, 1, 2, 3, 4, 5])

In [27]:
c  # Flattening is not done in-place

array([[0, 1, 2],
       [3, 4, 5]])

### Element-Wise Arithmetic Operations

In [28]:
a = np.array([20, 30, 40, 50])
a

array([20, 30, 40, 50])

In [29]:
b = np.arange(2, 6)
b

array([2, 3, 4, 5])

In [30]:
c = a + b
c

array([22, 33, 44, 55])

In [31]:
c = a - b
c

array([18, 27, 36, 45])

In [32]:
c = a * b
c

array([ 40,  90, 160, 250])

In [33]:
c = a / b
c

array([ 10.,  10.,  10.,  10.])

In [34]:
b ** 2

array([ 4,  9, 16, 25], dtype=int32)

In [35]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [36]:
np.exp(b) #Euler exponential

array([   7.3890561 ,   20.08553692,   54.59815003,  148.4131591 ])

In [37]:
np.sqrt(a)

array([ 4.47213595,  5.47722558,  6.32455532,  7.07106781])

In [38]:
a

array([20, 30, 40, 50])

In [39]:
a <= 35

array([ True,  True, False, False], dtype=bool)

### Compare with Lists

In [40]:
a = [20, 30, 40, 50]
a

[20, 30, 40, 50]

In [41]:
b = list(range(2, 6))
b

[2, 3, 4, 5]

In [42]:
a + b  # List concatination

[20, 30, 40, 50, 2, 3, 4, 5]

- `a - b` does not work. It's not defined for lists.

In [43]:
a * 2  # List repetition

[20, 30, 40, 50, 20, 30, 40, 50]

- `a / b` does not work. It's not defined for lists.

### Multiplication

In [44]:
A = np.array([[1,1], [0,1]]) 
A

array([[1, 1],
       [0, 1]])

In [45]:
B = np.array([[2,0], [3,4]])
B

array([[2, 0],
       [3, 4]])

In [46]:
A * B           # Elementwise product

array([[2, 0],
       [0, 4]])

In [47]:
np.dot(A, B)    # Matrix product

array([[5, 4],
       [3, 4]])

### Course Materials on YouTube and GitHub

- Course videos are hosted by YouTube ( http://youtube.com/yongtwang ).
- Course documents (Jupyter Notebooks and Python source code) are hosted by GitHub ( http://github.com/yongtwang ).